# Generated by Django 6.0.6 on 2026-06-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["created_date"]},
        ),
    ]
