# Generated by Django 6.0.6 on 2026-07-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_model"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Model",
            new_name="NewsLetterModel",
        ),
    ]
