# Generated by Django 6.0.6 on 2026-07-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_rename_model_newslettermodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
