# Generated by Django 6.0.6 on 2026-06-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="blog/"),
        ),
    ]
