# Generated by Django 6.0.6 on 2026-07-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_comment_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AddField(
            model_name="post",
            name="logged_in_required",
            field=models.BooleanField(default=False),
        ),
    ]
